services:
  api:
      build:
        args:
         ENVIRONMENT: development
      volumes:
         - .:/app
      command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload --forwarded-allow-ips "*" 
  db:
    ports:
      - "5432:5432"
  worker:
    volumes:
      - .:/app
  publisher:
    volumes:
      - .:/app
  redis:
    ports:
      - "6379:6379"
  prometheus:
    ports:
      - "9090:9090"
  cadvisor:
    ports:
      - "8080:8080"
  grafana:
    ports:
      - "3000:3000"
