"""add description to Product

Revision ID: 276650e33692
Revises: a836d7ed225c
Create Date: 2026-08-31 14:31:43.953643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '276650e33692'
down_revision: Union[str, Sequence[str], None] = 'a836d7ed225c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Product', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Product', 'description')
    # ### end Alembic commands ###
