server {
    listen 80;

    location / {
        return 301 https://$host$request_uri;
    }

    location /.well-known/acme-challenge/ {
        root /certbot/www;
    }
}

server {
    listen 443 ssl;
    server_name backend-portfolio-api.duckdns.org;
    
    ssl_certificate /etc/letsencrypt/live/backend-portfolio-api.duckdns.org/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/backend-portfolio-api.duckdns.org/privkey.pem;
    
    location / {
        proxy_pass http://api:8000;
    }

}