name: CI

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Set up Python
        uses: actions/setup-python@v7
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install -r requirements.dev.txt

      - name: Run tests
        env:
          DATABASE_URL: sqlite:///./ci.db
          SECRET_KEY: test-secret-key

        run: python -m pytest